[package]
name = "generate-number-combinations"
version = "0.1.0"
authors = ["Aborgen <alexanderborgen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
rayon = "1.5"
redis = "0.20.1"
